config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'chats/create'
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'daily_posts' => 'users#daily_posts'
  end
  
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  
  get '/search', to: 'searches#search'
  get '/search_book' => 'searches#search_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
  
  def self.search(search_word)
    Book.where(['tag LIKE?', "#{search_word}"])
  end
  
  # 今日
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  # 昨日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  # 2日前
  scope :created_2days, -> { where(created_at: 2.days.ago.all_day) } 
  # 3日前
  scope :created_3days, -> { where(created_at: 3.days.ago.all_day) } 
  # 4日前
  scope :created_4days, -> { where(created_at: 4.days.ago.all_day) } 
  # 5日前
  scope :created_5days, -> { where(created_at: 5.days.ago.all_day) } 
  # 6日前
  scope :created_6days, -> { where(created_at: 6.days.ago.all_day) } 
  # 今週
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  # 先週
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates:comment, presence:true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image

  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  
  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships,            class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships,            source: :followed
  has_many :followers,  through: :reverse_of_relationships, source: :follower
  has_many :view_counts, dependent: :destroy
  
  has_many :rooms, through: :user_rooms
  has_many :user_rooms
  has_many :chats
  
  has_many :group_users
  has_many :groups, through: :group_users

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def follow(user)
    relationships.create(followed_id: user.id)
  end
  
  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
    @user = current_user
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def index
    case params[:order]
    when 'created_at_desc'
      @books = Book.order(created_at: :desc)
    when 'star_desc'
      @books = Book.order(star: :desc)
    else
      @books = Book.left_joins(:favorites)
                   .group(:id)
                   .order('COUNT(favorites.id) DESC')
    end
    @newbook = Book.new
  end

  def create
    @newbook = Book.new(book_params)
    @newbook.user_id = current_user.id
    if @newbook.save
      redirect_to book_path(@newbook), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :tag, :star)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to request.referer
  end

  private
    def chat_params
      params.require(:chat).permit(:message, :room_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :Tag %>
    <%= f.text_field :tag, class: 'form-control book_body' %>
  </div>
  <div class="form-group" id="star">
    <%= f.label :star, '評価', class:'ol-md-3 col-form-label' %>
    <%= f.hidden_field :star, id: :review_star, class:'form-control' %>
  </div>
  <% if book.id === nil %>
    <script>
      // $('#star').empty();
      $('#star').raty({
        size:      36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn:   '<%= asset_path('star-on.png') %>',
        scoreName:'book[star]',
      });
    </script>
  <% else %>
    <%= render 'star_rate', book: book %>
  <% end %>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td>
          <%= link_to book.tag, search_book_path(keyword: book.tag) %>
        </td>
        <td id="favorite_btn_<%= book.id %>" class="favorite-btn"><%= render 'favorites/favorite', book: book %></td>
        <td>
          <p><%= "コメント数：#{book.book_comments.count}" %></p>
        </td>
        <td><%= render "books/star_rate", book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_star_rate.html.erb
<div id="star-rate<%= book.id %>" class="form-group"></div>
<script>
$(document).on('turbolinks:load', function(){
  $('#star-rate<%= book.id %>').empty();
  $('#star-rate<%= book.id %>').raty({
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= book.star %>,
  });
});
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render "devise/shared/error_messages", resource: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render "devise/shared/error_messages", resource: @newbook %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @newbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新しい順", {order: "created_at_desc"} %> | <%= link_to "評価の高い順", {order: "star_desc"} %>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @newbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"50x50" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>
            <%= link_to @book.tag, search_book_path(keyword: @book.tag) %>
          </td>
          <td id="favorite_btn_<%= @book.id %>" class="favorite-btn"><%= render 'favorites/favorite', book: @book %></td>
          <td class="book-comments-counter">
            <%= render "book_comments/counter", book: @book %>
          </td>
          <!--<td>閲覧数: <%= @book.view_counts.count %></td>-->
          <td><%= render 'star_rate', book: @book %></td>
          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </table>
    　<div class="book-comments-index">
        <%= render "book_comments/index", book: @book %>
      </div>
      <div>
        <%= render "book_comments/form", book: @book, book_comment: @comment %>
      </div>
    </div>
  </div>
</div>

app/views/chats/create.html.erb
<h1>Chats#create</h1>
<p>Find me in app/views/chats/create.html.erb</p>

app/views/chats/show.html.erb
<%= form_with model: @chat do |f| %>
    <%= f.text_field :message %>
    <%= f.hidden_field :room_id %>
    <%= f.submit %>
<% end %>
<table>
  <thead>
    <tr>
      <td>投稿者名</td>
      <td>投稿内容</td>
    </tr>
  </thead>
  <tbody>
      <% @chats.each do |chat| %>
          <tr>
            <td><%= chat.user.name %></td>
            <td><%= chat.message %></td>
          </tr>
      <% end %>
  </tbody>
</table>